# Generated by Django 5.0.6 on 2024-05-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
